#define ID_APPNAME   1
#define ID_MAINMENU	1
#define ID_MAINICON	1
#define ID_MAINACCEL	1

// other window messages
#define WM_UPDATEFORMULA   WM_USER
#define WM_CREATEEDIT         WM_USER+1
#define WM_REMOVEEDIT         WM_USER+2
#define WM_SETFORMULATXT    WM_USER+3
#define WM_INCELLEDIT          WM_USER+4
#define WM_GETEDITVIEW   WM_USER+5

// menu ids
#define MID_FILE        1000
#define MID_FILE_NEW       (MID_FILE +1)
#define MID_FILE_OPEN      (MID_FILE +2)
#define MID_FILE_SAVE      (MID_FILE +3)
#define MID_FILE_SAVEAS   (MID_FILE +4)
#define MID_FILE_PRINT     (MID_FILE +5)
#define MID_FILE_EXIT	  (MID_FILE +7)

#define IDD_LOAN_AMORTIZATION	2000
#define DID_LOANID	(IDD_LOAN_AMORTIZATION+1)
#define DID_APPDATE	(IDD_LOAN_AMORTIZATION+2)
#define DID_REP	(IDD_LOAN_AMORTIZATION+3)
#define DID_APPNAME	(IDD_LOAN_AMORTIZATION+4)
#define DID_SSNO	(IDD_LOAN_AMORTIZATION+5)
#define DID_EMPLOYER	(IDD_LOAN_AMORTIZATION+6)
#define DID_WORKPHONE	(IDD_LOAN_AMORTIZATION+7)
#define DID_HOMEPHONE	(IDD_LOAN_AMORTIZATION+8)
#define DID_TYPE	(IDD_LOAN_AMORTIZATION+9)
#define DID_RATE	(IDD_LOAN_AMORTIZATION+10)
#define DID_AMOUNT	(IDD_LOAN_AMORTIZATION+11)
#define DID_STDATE	(IDD_LOAN_AMORTIZATION +12)
#define DID_DURATION	(IDD_LOAN_AMORTIZATION+13)
#define DID_PERIODICITY (IDD_LOAN_AMORTIZATION+14)

#define IDD_VIEWSHEET      3000
#define DID_SHEETVIEW    (IDD_VIEWSHEET+1)
#define DID_INCELL       (IDD_VIEWSHEET+2)
#define DID_FORMULA      (IDD_VIEWSHEET+3)
